services:
  leantime_db:
    image: mysql:8.0
    container_name: mysql_leantime
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    env_file: ./.env # Environment file with settings
    networks:
      - leantime-net
    command: --character-set-server=UTF8MB4 --collation-server=UTF8MB4_unicode_ci

  leantime:
    image: leantime/leantime:latest
    container_name: leantime
    restart: unless-stopped
    env_file: ./.env # Environment file with settings
    networks:
      - leantime-net
      - multi-domain

    volumes:
      - public_userfiles:/var/www/html/public/userfiles # Volume to store public files, logo etc
      - userfiles:/var/www/html/userfiles # Volume to store private user uploaded files
      - config:/var/www/html/config/
    expose:
      - 80
    #ports:
    #  - "${LEAN_PORT}:80"                                          # The port to expose and access Leantime
    depends_on:
      - leantime_db # Don't start Leantime unless leantime_db is running

volumes:
  db_data:
    name: sab_leantime_db_data
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: ./volumes/db_data
  userfiles:
    name: sab_leantime_userfiles
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: ./volumes/userfiles
  public_userfiles:
    name: sab_leantime_public_userfiles
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: ./volumes/public_userfiles
  config:
    name: sab_leantime_config
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: ./volumes/config

networks:
  leantime-net:
  multi-domain:
    name: multi-domain
    external: true
